### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by ItsAleph** [NoEnd-yt/godot-dash#8]
I looked a bit at how everything works and i believe supporting Android is just a matter of enabling mouse click emulation in project settings, though i might be mistaken.

Also, great job on this!

**Comment by NoEnd-yt** [comment]
I didn't know about that, thanks.
My issue at the moment is that I have no idea how to export to Android. I'll close this issue as soon as I figure it out.

**Comment by NoEnd-yt** [comment]
Compiling isn't the only issue though, some places might look off with a phone's wide screen. I'll look into that as soon as I can.

**Comment by NoEnd-yt** [comment]
Fixed in v1.11.

**Comment by ItsAleph** [comment]
Thanks!
